[MeterSpectrum]
Meter=Shape
X=0
Y=0
; ---------------------------------------------------------------------------------------------
Shape=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand0]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke#
; ---------------------------------------------------------------------------------------------
Shape2=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand1]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*1),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape3=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand2]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*2),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape4=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand3]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*3),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape5=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand4]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*4),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape6=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand5]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*5),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape7=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand6]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*6),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape8=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand7]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*7),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape9=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand8]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*8),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape10=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand9]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*9),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape11=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand10]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*10),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape12=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand11]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*11),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape13=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand12]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*12),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape14=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand13]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*13),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape15=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand14]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*14),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape16=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand15]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*15),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape17=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand16]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*16),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape18=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand17]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*17),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape19=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand18]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*18),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape20=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand19]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*19),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape21=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand20]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*20),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape22=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand21]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*21),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape23=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand22]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*22),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape24=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand23]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*23),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape25=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand24]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*24),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape26=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand25]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*25),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape27=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand26]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*26),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape28=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand27]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*27),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape29=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand28]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*28),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape30=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand29]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*29),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape31=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand30]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*30),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape32=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand31]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*31),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape33=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand32]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*32),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape34=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand33]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*33),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape35=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand34]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*34),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape36=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand35]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*35),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape37=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand36]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*36),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape38=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand37]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*37),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape39=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand38]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*38),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape40=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand39]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*39),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape41=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand40]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*40),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape42=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand41]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*41),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape43=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand42]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*42),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape44=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand43]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*43),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape45=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand44]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*44),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape46=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand45]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*45),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape47=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand46]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*46),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape48=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand47]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*47),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape49=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand48]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*48),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape50=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand49]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*49),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape51=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand50]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*50),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape52=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand51]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*51),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape53=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand52]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*52),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape54=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand53]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*53),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape55=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand54]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*54),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape56=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand55]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*55),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape57=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand56]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*56),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape58=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand57]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*57),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape59=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand58]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*58),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape60=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand59]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*59),(#BarYR#)
; ---------------------------------------------------------------------------------------------
DynamicVariables=1
