[MeterSpectrum]
Meter=Shape
X=0
Y=0
; ---------------------------------------------------------------------------------------------
Shape=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand0]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke#
; ---------------------------------------------------------------------------------------------
Shape2=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand1]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*1),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape3=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand2]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*2),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape4=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand3]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*3),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape5=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand4]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*4),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape6=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand5]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*5),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape7=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand6]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*6),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape8=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand7]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*7),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape9=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand8]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*8),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape10=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand9]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*9),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape11=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand10]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*10),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape12=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand11]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*11),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape13=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand12]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*12),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape14=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand13]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*13),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape15=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand14]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*14),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape16=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand15]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*15),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape17=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand16]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*16),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape18=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand17]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*17),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape19=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand18]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*18),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape20=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand19]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*19),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape21=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand20]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*20),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape22=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand21]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*21),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape23=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand22]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*22),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape24=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand23]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*23),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape25=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand24]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*24),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape26=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand25]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*25),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape27=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand26]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*26),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape28=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand27]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*27),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape29=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand28]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*28),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape30=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand29]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*29),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape31=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand30]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*30),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape32=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand31]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*31),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape33=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand32]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*32),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape34=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand33]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*33),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape35=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand34]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*34),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape36=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand35]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*35),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape37=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand36]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*36),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape38=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand37]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*37),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape39=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand38]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*38),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape40=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand39]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*39),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape41=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand40]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*40),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape42=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand41]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*41),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape43=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand42]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*42),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape44=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand43]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*43),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape45=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand44]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*44),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape46=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand45]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*45),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape47=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand46]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*46),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape48=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand47]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*47),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape49=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand48]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*48),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape50=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand49]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*49),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape51=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand50]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*50),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape52=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand51]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*51),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape53=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand52]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*52),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape54=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand53]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*53),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape55=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand54]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*54),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape56=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand55]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*55),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape57=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand56]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*56),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape58=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand57]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*57),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape59=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand58]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*58),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape60=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand59]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*59),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape61=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand60]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*60),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape62=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand61]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*61),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape63=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand62]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*62),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape64=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand63]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*63),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape65=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand64]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*64),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape66=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand65]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*65),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape67=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand66]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*66),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape68=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand67]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*67),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape69=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand68]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*68),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape70=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand69]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*69),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape71=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand70]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*70),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape72=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand71]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*71),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape73=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand72]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*72),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape74=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand73]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*73),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape75=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand74]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*74),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape76=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand75]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*75),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape77=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand76]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*76),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape78=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand77]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*77),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape79=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand78]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*78),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape80=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand79]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*79),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape81=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand80]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*80),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape82=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand81]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*81),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape83=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand82]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*82),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape84=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand83]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*83),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape85=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand84]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*84),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape86=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand85]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*85),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape87=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand86]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*86),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape88=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand87]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*87),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape89=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand88]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*88),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape90=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand89]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*89),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape91=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand90]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*90),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape92=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand91]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*91),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape93=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand92]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*92),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape94=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand93]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*93),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape95=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand94]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*94),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape96=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand95]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*95),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape97=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand96]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*96),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape98=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand97]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*97),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape99=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand98]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*98),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape100=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand99]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*99),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape101=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand100]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*100),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape102=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand101]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*101),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape103=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand102]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*102),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape104=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand103]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*103),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape105=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand104]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*104),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape106=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand105]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*105),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape107=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand106]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*106),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape108=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand107]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*107),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape109=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand108]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*108),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape110=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand109]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*109),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape111=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand110]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*110),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape112=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand111]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*111),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape113=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand112]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*112),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape114=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand113]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*113),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape115=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand114]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*114),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape116=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand115]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*115),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape117=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand116]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*116),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape118=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand117]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*117),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape119=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand118]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*118),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape120=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand119]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*119),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape121=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand120]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*120),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape122=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand121]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*121),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape123=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand122]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*122),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape124=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand123]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*123),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape125=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand124]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*124),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape126=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand125]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*125),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape127=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand126]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*126),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape128=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand127]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*127),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape129=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand128]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*128),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape130=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand129]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*129),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape131=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand130]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*130),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape132=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand131]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*131),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape133=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand132]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*132),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape134=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand133]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*133),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape135=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand134]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*134),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape136=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand135]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*135),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape137=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand136]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*136),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape138=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand137]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*137),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape139=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand138]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*138),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape140=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand139]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*139),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape141=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand140]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*140),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape142=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand141]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*141),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape143=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand142]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*142),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape144=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand143]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*143),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape145=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand144]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*144),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape146=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand145]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*145),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape147=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand146]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*146),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape148=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand147]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*147),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape149=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand148]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*148),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape150=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand149]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*149),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape151=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand150]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*150),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape152=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand151]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*151),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape153=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand152]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*152),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape154=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand153]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*153),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape155=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand154]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*154),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape156=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand155]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*155),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape157=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand156]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*156),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape158=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand157]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*157),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape159=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand158]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*158),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape160=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand159]/1 * (#MaxHeight#-#MinHeight#) + #MinHeight#)),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*159),(#BarYR#)
; ---------------------------------------------------------------------------------------------
DynamicVariables=1
