[MeterSpectrum]
Meter=Shape
X=0
Y=0
; ---------------------------------------------------------------------------------------------
Shape=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand0])),#Radius# | #Fill# | #Stroke#
; ---------------------------------------------------------------------------------------------
Shape2=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand1])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*1),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape3=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand2])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*2),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape4=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand3])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*3),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape5=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand4])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*4),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape6=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand5])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*5),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape7=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand6])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*6),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape8=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand7])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*7),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape9=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand8])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*8),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape10=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand9])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*9),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape11=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand10])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*10),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape12=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand11])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*11),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape13=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand12])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*12),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape14=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand13])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*13),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape15=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand14])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*14),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape16=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand15])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*15),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape17=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand16])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*16),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape18=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand17])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*17),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape19=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand18])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*18),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape20=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand19])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*19),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape21=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand20])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*20),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape22=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand21])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*21),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape23=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand22])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*22),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape24=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand23])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*23),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape25=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand24])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*24),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape26=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand25])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*25),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape27=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand26])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*26),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape28=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand27])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*27),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape29=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand28])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*28),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape30=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand29])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*29),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape31=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand30])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*30),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape32=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand31])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*31),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape33=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand32])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*32),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape34=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand33])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*33),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape35=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand34])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*34),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape36=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand35])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*35),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape37=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand36])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*36),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape38=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand37])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*37),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape39=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand38])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*38),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape40=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand39])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*39),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape41=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand40])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*40),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape42=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand41])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*41),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape43=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand42])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*42),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape44=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand43])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*43),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape45=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand44])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*44),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape46=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand45])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*45),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape47=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand46])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*46),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape48=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand47])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*47),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape49=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand48])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*48),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape50=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand49])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*49),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape51=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand50])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*50),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape52=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand51])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*51),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape53=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand52])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*52),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape54=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand53])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*53),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape55=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand54])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*54),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape56=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand55])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*55),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape57=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand56])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*56),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape58=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand57])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*57),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape59=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand58])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*58),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape60=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand59])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*59),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape61=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand60])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*60),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape62=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand61])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*61),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape63=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand62])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*62),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape64=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand63])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*63),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape65=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand64])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*64),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape66=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand65])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*65),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape67=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand66])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*66),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape68=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand67])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*67),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape69=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand68])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*68),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape70=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand69])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*69),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape71=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand70])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*70),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape72=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand71])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*71),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape73=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand72])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*72),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape74=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand73])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*73),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape75=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand74])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*74),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape76=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand75])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*75),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape77=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand76])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*76),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape78=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand77])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*77),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape79=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand78])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*78),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape80=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand79])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*79),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape81=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand80])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*80),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape82=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand81])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*81),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape83=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand82])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*82),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape84=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand83])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*83),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape85=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand84])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*84),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape86=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand85])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*85),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape87=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand86])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*86),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape88=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand87])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*87),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape89=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand88])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*88),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape90=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand89])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*89),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape91=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand90])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*90),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape92=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand91])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*91),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape93=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand92])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*92),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape94=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand93])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*93),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape95=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand94])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*94),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape96=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand95])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*95),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape97=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand96])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*96),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape98=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand97])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*97),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape99=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand98])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*98),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape100=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand99])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*99),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape101=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand100])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*100),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape102=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand101])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*101),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape103=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand102])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*102),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape104=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand103])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*103),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape105=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand104])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*104),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape106=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand105])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*105),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape107=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand106])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*106),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape108=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand107])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*107),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape109=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand108])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*108),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape110=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand109])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*109),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape111=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand110])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*110),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape112=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand111])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*111),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape113=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand112])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*112),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape114=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand113])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*113),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape115=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand114])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*114),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape116=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand115])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*115),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape117=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand116])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*116),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape118=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand117])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*117),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape119=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand118])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*118),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape120=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand119])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*119),(#BarYR#)
; ---------------------------------------------------------------------------------------------
DynamicVariables=1
