[Variables]
Fps=60
UpdateRate=(1000 / #Fps#)
; ------------
BarWidth=5
BarsGab=0.2
; ------------
MaxHeight=100
Color=210,210,230,230
; ------------
; Common settings
; ------------
FreqMin=20
FreqMax=2000
Bands=120
; ------------
Attack=100
Decay=100
; ------------
; AudioLevel Specfic
; ------------
FFTSize=4096*4
Sensitivity=41
; ------------
; AudioAnalyzer Specfic
; ------------
BinWidth=10
OverlapBoost=10
CascadesCount=4
; ------------
BlurRadius=1
RadiusAdaptation=1