[Variables]
@Include=#@#Variables/LevelColors.inc

[LevelShapesBL]
Shape=Rectangle   (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#BLeftX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesSL]
Shape=Rectangle   (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#SLeftX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesFL]
Shape=Rectangle   (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#FLeftX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesC]
Shape=Rectangle   (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#CenterX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesFR]
Shape=Rectangle   (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#FRightX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesSR]
Shape=Rectangle   (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#SRightX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesBR]
Shape=Rectangle   (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#BRightX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[MeasureBar]
Measure=Calc
Formula=0
UpdateDivider=-1
