[Variables]
@Include=#@#Variables/LevelColors.inc

[LevelShapes]
Shape=Rectangle   (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#X#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesL]
Shape=Rectangle   (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#LeftX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[LevelShapesR]
Shape=Rectangle   (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor1# | StrokeWidth 0 | Offset 0,0
Shape2=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor2# | StrokeWidth 0 | Offset 0,(12.5*1)
Shape3=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor3# | StrokeWidth 0 | Offset 0,(12.5*2)
Shape4=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor4# | StrokeWidth 0 | Offset 0,(12.5*3)
Shape5=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor5# | StrokeWidth 0 | Offset 0,(12.5*4)
Shape6=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor6# | StrokeWidth 0 | Offset 0,(12.5*5)
Shape7=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor7# | StrokeWidth 0 | Offset 0,(12.5*6)
Shape8=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor8# | StrokeWidth 0 | Offset 0,(12.5*7)
Shape9=Rectangle  (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor9# | StrokeWidth 0 | Offset 0,(12.5*8)
Shape10=Rectangle (Neg(#RightX#)),0,30,10,5 | Fill Color #LevelColor10# | StrokeWidth 0 | Offset 0,(12.5*9)

[MeasureBar]
Measure=Calc
Formula=0
UpdateDivider=-1