[MeasureBand0]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=0
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand1]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=1
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand2]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=2
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand3]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=3
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand4]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=4
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand5]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=5
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand6]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=6
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand7]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=7
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand8]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=8
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand9]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=9
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand10]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=10
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=11
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=12
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=13
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=14
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=15
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=16
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=17
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=18
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=19
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand20]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=20
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=21
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=22
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=23
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=24
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=25
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=26
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=27
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=28
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=29
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand30]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=30
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=31
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=32
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=33
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=34
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=35
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=36
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=37
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=38
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=39
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand40]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=40
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand41]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=41
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand42]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=42
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand43]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=43
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand44]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=44
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand45]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=45
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand46]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=46
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand47]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=47
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand48]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=48
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand49]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=49
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand50]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=50
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand51]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=51
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand52]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=52
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand53]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=53
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand54]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=54
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand55]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=55
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand56]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=56
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand57]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=57
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand58]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=58
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand59]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=59
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand60]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=60
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand61]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=61
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand62]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=62
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand63]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=63
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand64]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=64
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand65]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=65
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand66]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=66
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand67]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=67
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand68]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=68
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand69]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=69
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand70]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=70
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand71]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=71
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand72]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=72
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand73]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=73
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand74]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=74
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand75]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=75
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand76]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=76
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand77]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=77
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand78]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=78
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand79]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=79
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand80]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=80
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand81]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=81
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand82]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=82
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand83]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=83
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand84]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=84
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand85]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=85
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand86]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=86
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand87]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=87
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand88]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=88
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand89]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=89
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand90]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=90
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand91]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=91
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand92]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=92
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand93]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=93
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand94]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=94
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand95]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=95
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand96]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=96
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand97]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=97
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand98]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=98
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand99]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=99
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand100]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=100
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand101]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=101
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand102]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=102
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand103]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=103
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand104]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=104
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand105]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=105
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand106]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=106
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand107]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=107
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand108]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=108
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand109]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=109
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand110]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=110
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand111]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=111
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand112]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=112
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand113]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=113
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand114]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=114
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand115]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=115
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand116]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=116
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand117]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=117
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand118]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=118
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand119]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=119
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand120]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=120
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand121]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=121
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand122]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=122
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand123]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=123
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand124]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=124
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand125]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=125
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand126]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=126
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand127]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=127
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand128]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=128
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand129]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=129
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand130]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=130
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand131]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=131
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand132]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=132
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand133]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=133
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand134]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=134
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand135]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=135
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand136]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=136
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand137]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=137
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand138]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=138
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand139]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=139
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand140]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=140
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand141]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=141
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand142]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=142
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand143]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=143
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand144]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=144
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand145]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=145
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand146]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=146
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand147]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=147
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand148]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=148
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand149]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=149
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand150]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=150
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand151]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=151
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand152]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=152
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand153]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=153
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand154]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=154
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand155]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=155
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand156]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=156
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand157]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=157
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand158]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=158
Channel=Auto
HandlerName=MainFinalOutput

[MeasureBand159]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=159
Channel=Auto
HandlerName=MainFinalOutput

