[MeasureBand0]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=0
Channel=Auto
HandlerName=ReMaper

[MeasureBand1]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=1
Channel=Auto
HandlerName=ReMaper

[MeasureBand2]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=2
Channel=Auto
HandlerName=ReMaper

[MeasureBand3]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=3
Channel=Auto
HandlerName=ReMaper

[MeasureBand4]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=4
Channel=Auto
HandlerName=ReMaper

[MeasureBand5]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=5
Channel=Auto
HandlerName=ReMaper

[MeasureBand6]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=6
Channel=Auto
HandlerName=ReMaper

[MeasureBand7]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=7
Channel=Auto
HandlerName=ReMaper

[MeasureBand8]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=8
Channel=Auto
HandlerName=ReMaper

[MeasureBand9]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=9
Channel=Auto
HandlerName=ReMaper

[MeasureBand10]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=10
Channel=Auto
HandlerName=ReMaper

[MeasureBand11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=11
Channel=Auto
HandlerName=ReMaper

[MeasureBand12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=12
Channel=Auto
HandlerName=ReMaper

[MeasureBand13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=13
Channel=Auto
HandlerName=ReMaper

[MeasureBand14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=14
Channel=Auto
HandlerName=ReMaper

[MeasureBand15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=15
Channel=Auto
HandlerName=ReMaper

[MeasureBand16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=16
Channel=Auto
HandlerName=ReMaper

[MeasureBand17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=17
Channel=Auto
HandlerName=ReMaper

[MeasureBand18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=18
Channel=Auto
HandlerName=ReMaper

[MeasureBand19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=19
Channel=Auto
HandlerName=ReMaper

[MeasureBand20]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=20
Channel=Auto
HandlerName=ReMaper

[MeasureBand21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=21
Channel=Auto
HandlerName=ReMaper

[MeasureBand22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=22
Channel=Auto
HandlerName=ReMaper

[MeasureBand23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=23
Channel=Auto
HandlerName=ReMaper

[MeasureBand24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=24
Channel=Auto
HandlerName=ReMaper

[MeasureBand25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=25
Channel=Auto
HandlerName=ReMaper

[MeasureBand26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=26
Channel=Auto
HandlerName=ReMaper

[MeasureBand27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=27
Channel=Auto
HandlerName=ReMaper

[MeasureBand28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=28
Channel=Auto
HandlerName=ReMaper

[MeasureBand29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=29
Channel=Auto
HandlerName=ReMaper

[MeasureBand30]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=30
Channel=Auto
HandlerName=ReMaper

[MeasureBand31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=31
Channel=Auto
HandlerName=ReMaper

[MeasureBand32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=32
Channel=Auto
HandlerName=ReMaper

[MeasureBand33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=33
Channel=Auto
HandlerName=ReMaper

[MeasureBand34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=34
Channel=Auto
HandlerName=ReMaper

[MeasureBand35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=35
Channel=Auto
HandlerName=ReMaper

[MeasureBand36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=36
Channel=Auto
HandlerName=ReMaper

[MeasureBand37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=37
Channel=Auto
HandlerName=ReMaper

[MeasureBand38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=38
Channel=Auto
HandlerName=ReMaper

[MeasureBand39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=39
Channel=Auto
HandlerName=ReMaper

[MeasureBand40]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=40
Channel=Auto
HandlerName=ReMaper

[MeasureBand41]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=41
Channel=Auto
HandlerName=ReMaper

[MeasureBand42]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=42
Channel=Auto
HandlerName=ReMaper

[MeasureBand43]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=43
Channel=Auto
HandlerName=ReMaper

[MeasureBand44]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=44
Channel=Auto
HandlerName=ReMaper

[MeasureBand45]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=45
Channel=Auto
HandlerName=ReMaper

[MeasureBand46]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=46
Channel=Auto
HandlerName=ReMaper

[MeasureBand47]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=47
Channel=Auto
HandlerName=ReMaper

[MeasureBand48]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=48
Channel=Auto
HandlerName=ReMaper

[MeasureBand49]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=49
Channel=Auto
HandlerName=ReMaper

[MeasureBand50]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=50
Channel=Auto
HandlerName=ReMaper

[MeasureBand51]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=51
Channel=Auto
HandlerName=ReMaper

[MeasureBand52]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=52
Channel=Auto
HandlerName=ReMaper

[MeasureBand53]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=53
Channel=Auto
HandlerName=ReMaper

[MeasureBand54]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=54
Channel=Auto
HandlerName=ReMaper

[MeasureBand55]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=55
Channel=Auto
HandlerName=ReMaper

[MeasureBand56]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=56
Channel=Auto
HandlerName=ReMaper

[MeasureBand57]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=57
Channel=Auto
HandlerName=ReMaper

[MeasureBand58]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=58
Channel=Auto
HandlerName=ReMaper

[MeasureBand59]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=59
Channel=Auto
HandlerName=ReMaper

[MeasureBand60]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=60
Channel=Auto
HandlerName=ReMaper

[MeasureBand61]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=61
Channel=Auto
HandlerName=ReMaper

[MeasureBand62]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=62
Channel=Auto
HandlerName=ReMaper

[MeasureBand63]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=63
Channel=Auto
HandlerName=ReMaper

[MeasureBand64]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=64
Channel=Auto
HandlerName=ReMaper

[MeasureBand65]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=65
Channel=Auto
HandlerName=ReMaper

[MeasureBand66]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=66
Channel=Auto
HandlerName=ReMaper

[MeasureBand67]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=67
Channel=Auto
HandlerName=ReMaper

[MeasureBand68]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=68
Channel=Auto
HandlerName=ReMaper

[MeasureBand69]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=69
Channel=Auto
HandlerName=ReMaper

[MeasureBand70]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=70
Channel=Auto
HandlerName=ReMaper

[MeasureBand71]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=71
Channel=Auto
HandlerName=ReMaper

[MeasureBand72]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=72
Channel=Auto
HandlerName=ReMaper

[MeasureBand73]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=73
Channel=Auto
HandlerName=ReMaper

[MeasureBand74]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=74
Channel=Auto
HandlerName=ReMaper

[MeasureBand75]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=75
Channel=Auto
HandlerName=ReMaper

[MeasureBand76]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=76
Channel=Auto
HandlerName=ReMaper

[MeasureBand77]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=77
Channel=Auto
HandlerName=ReMaper

[MeasureBand78]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=78
Channel=Auto
HandlerName=ReMaper

[MeasureBand79]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=79
Channel=Auto
HandlerName=ReMaper

[MeasureBand80]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=80
Channel=Auto
HandlerName=ReMaper

[MeasureBand81]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=81
Channel=Auto
HandlerName=ReMaper

[MeasureBand82]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=82
Channel=Auto
HandlerName=ReMaper

[MeasureBand83]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=83
Channel=Auto
HandlerName=ReMaper

[MeasureBand84]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=84
Channel=Auto
HandlerName=ReMaper

[MeasureBand85]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=85
Channel=Auto
HandlerName=ReMaper

[MeasureBand86]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=86
Channel=Auto
HandlerName=ReMaper

[MeasureBand87]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=87
Channel=Auto
HandlerName=ReMaper

[MeasureBand88]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=88
Channel=Auto
HandlerName=ReMaper

[MeasureBand89]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=89
Channel=Auto
HandlerName=ReMaper

[MeasureBand90]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=90
Channel=Auto
HandlerName=ReMaper

[MeasureBand91]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=91
Channel=Auto
HandlerName=ReMaper

[MeasureBand92]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=92
Channel=Auto
HandlerName=ReMaper

[MeasureBand93]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=93
Channel=Auto
HandlerName=ReMaper

[MeasureBand94]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=94
Channel=Auto
HandlerName=ReMaper

[MeasureBand95]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=95
Channel=Auto
HandlerName=ReMaper

[MeasureBand96]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=96
Channel=Auto
HandlerName=ReMaper

[MeasureBand97]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=97
Channel=Auto
HandlerName=ReMaper

[MeasureBand98]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=98
Channel=Auto
HandlerName=ReMaper

[MeasureBand99]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=99
Channel=Auto
HandlerName=ReMaper

[MeasureBand100]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=100
Channel=Auto
HandlerName=ReMaper

[MeasureBand101]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=101
Channel=Auto
HandlerName=ReMaper

[MeasureBand102]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=102
Channel=Auto
HandlerName=ReMaper

[MeasureBand103]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=103
Channel=Auto
HandlerName=ReMaper

[MeasureBand104]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=104
Channel=Auto
HandlerName=ReMaper

[MeasureBand105]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=105
Channel=Auto
HandlerName=ReMaper

[MeasureBand106]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=106
Channel=Auto
HandlerName=ReMaper

[MeasureBand107]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=107
Channel=Auto
HandlerName=ReMaper

[MeasureBand108]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=108
Channel=Auto
HandlerName=ReMaper

[MeasureBand109]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=109
Channel=Auto
HandlerName=ReMaper

[MeasureBand110]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=110
Channel=Auto
HandlerName=ReMaper

[MeasureBand111]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=111
Channel=Auto
HandlerName=ReMaper

[MeasureBand112]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=112
Channel=Auto
HandlerName=ReMaper

[MeasureBand113]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=113
Channel=Auto
HandlerName=ReMaper

[MeasureBand114]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=114
Channel=Auto
HandlerName=ReMaper

[MeasureBand115]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=115
Channel=Auto
HandlerName=ReMaper

[MeasureBand116]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=116
Channel=Auto
HandlerName=ReMaper

[MeasureBand117]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=117
Channel=Auto
HandlerName=ReMaper

[MeasureBand118]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=118
Channel=Auto
HandlerName=ReMaper

[MeasureBand119]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=119
Channel=Auto
HandlerName=ReMaper

[MeasureBand120]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=120
Channel=Auto
HandlerName=ReMaper

[MeasureBand121]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=121
Channel=Auto
HandlerName=ReMaper

[MeasureBand122]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=122
Channel=Auto
HandlerName=ReMaper

[MeasureBand123]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=123
Channel=Auto
HandlerName=ReMaper

[MeasureBand124]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=124
Channel=Auto
HandlerName=ReMaper

[MeasureBand125]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=125
Channel=Auto
HandlerName=ReMaper

[MeasureBand126]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=126
Channel=Auto
HandlerName=ReMaper

[MeasureBand127]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=127
Channel=Auto
HandlerName=ReMaper

[MeasureBand128]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=128
Channel=Auto
HandlerName=ReMaper

[MeasureBand129]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=129
Channel=Auto
HandlerName=ReMaper

[MeasureBand130]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=130
Channel=Auto
HandlerName=ReMaper

[MeasureBand131]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=131
Channel=Auto
HandlerName=ReMaper

[MeasureBand132]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=132
Channel=Auto
HandlerName=ReMaper

[MeasureBand133]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=133
Channel=Auto
HandlerName=ReMaper

[MeasureBand134]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=134
Channel=Auto
HandlerName=ReMaper

[MeasureBand135]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=135
Channel=Auto
HandlerName=ReMaper

[MeasureBand136]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=136
Channel=Auto
HandlerName=ReMaper

[MeasureBand137]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=137
Channel=Auto
HandlerName=ReMaper

[MeasureBand138]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=138
Channel=Auto
HandlerName=ReMaper

[MeasureBand139]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=139
Channel=Auto
HandlerName=ReMaper

[MeasureBand140]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=140
Channel=Auto
HandlerName=ReMaper

[MeasureBand141]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=141
Channel=Auto
HandlerName=ReMaper

[MeasureBand142]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=142
Channel=Auto
HandlerName=ReMaper

[MeasureBand143]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=143
Channel=Auto
HandlerName=ReMaper

[MeasureBand144]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=144
Channel=Auto
HandlerName=ReMaper

[MeasureBand145]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=145
Channel=Auto
HandlerName=ReMaper

[MeasureBand146]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=146
Channel=Auto
HandlerName=ReMaper

[MeasureBand147]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=147
Channel=Auto
HandlerName=ReMaper

[MeasureBand148]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=148
Channel=Auto
HandlerName=ReMaper

[MeasureBand149]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=149
Channel=Auto
HandlerName=ReMaper

[MeasureBand150]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=150
Channel=Auto
HandlerName=ReMaper

[MeasureBand151]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=151
Channel=Auto
HandlerName=ReMaper

[MeasureBand152]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=152
Channel=Auto
HandlerName=ReMaper

[MeasureBand153]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=153
Channel=Auto
HandlerName=ReMaper

[MeasureBand154]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=154
Channel=Auto
HandlerName=ReMaper

[MeasureBand155]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=155
Channel=Auto
HandlerName=ReMaper

[MeasureBand156]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=156
Channel=Auto
HandlerName=ReMaper

[MeasureBand157]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=157
Channel=Auto
HandlerName=ReMaper

[MeasureBand158]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=158
Channel=Auto
HandlerName=ReMaper

[MeasureBand159]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=159
Channel=Auto
HandlerName=ReMaper

[MeasureBand160]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=160
Channel=Auto
HandlerName=ReMaper

[MeasureBand161]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=161
Channel=Auto
HandlerName=ReMaper

[MeasureBand162]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=162
Channel=Auto
HandlerName=ReMaper

[MeasureBand163]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=163
Channel=Auto
HandlerName=ReMaper

[MeasureBand164]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=164
Channel=Auto
HandlerName=ReMaper

[MeasureBand165]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=165
Channel=Auto
HandlerName=ReMaper

[MeasureBand166]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=166
Channel=Auto
HandlerName=ReMaper

[MeasureBand167]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=167
Channel=Auto
HandlerName=ReMaper

[MeasureBand168]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=168
Channel=Auto
HandlerName=ReMaper

[MeasureBand169]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=169
Channel=Auto
HandlerName=ReMaper

[MeasureBand170]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=170
Channel=Auto
HandlerName=ReMaper

[MeasureBand171]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=171
Channel=Auto
HandlerName=ReMaper

[MeasureBand172]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=172
Channel=Auto
HandlerName=ReMaper

[MeasureBand173]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=173
Channel=Auto
HandlerName=ReMaper

[MeasureBand174]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=174
Channel=Auto
HandlerName=ReMaper

[MeasureBand175]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=175
Channel=Auto
HandlerName=ReMaper

[MeasureBand176]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=176
Channel=Auto
HandlerName=ReMaper

[MeasureBand177]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=177
Channel=Auto
HandlerName=ReMaper

[MeasureBand178]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=178
Channel=Auto
HandlerName=ReMaper

[MeasureBand179]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=179
Channel=Auto
HandlerName=ReMaper

[MeasureBand180]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=180
Channel=Auto
HandlerName=ReMaper

[MeasureBand181]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=181
Channel=Auto
HandlerName=ReMaper

[MeasureBand182]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=182
Channel=Auto
HandlerName=ReMaper

[MeasureBand183]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=183
Channel=Auto
HandlerName=ReMaper

[MeasureBand184]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=184
Channel=Auto
HandlerName=ReMaper

[MeasureBand185]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=185
Channel=Auto
HandlerName=ReMaper

[MeasureBand186]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=186
Channel=Auto
HandlerName=ReMaper

[MeasureBand187]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=187
Channel=Auto
HandlerName=ReMaper

[MeasureBand188]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=188
Channel=Auto
HandlerName=ReMaper

[MeasureBand189]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=189
Channel=Auto
HandlerName=ReMaper

[MeasureBand190]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=190
Channel=Auto
HandlerName=ReMaper

[MeasureBand191]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=191
Channel=Auto
HandlerName=ReMaper

[MeasureBand192]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=192
Channel=Auto
HandlerName=ReMaper

[MeasureBand193]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=193
Channel=Auto
HandlerName=ReMaper

[MeasureBand194]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=194
Channel=Auto
HandlerName=ReMaper

[MeasureBand195]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=195
Channel=Auto
HandlerName=ReMaper

[MeasureBand196]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=196
Channel=Auto
HandlerName=ReMaper

[MeasureBand197]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=197
Channel=Auto
HandlerName=ReMaper

[MeasureBand198]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=198
Channel=Auto
HandlerName=ReMaper

[MeasureBand199]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=199
Channel=Auto
HandlerName=ReMaper

[MeasureBand200]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=200
Channel=Auto
HandlerName=ReMaper

[MeasureBand201]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=201
Channel=Auto
HandlerName=ReMaper

[MeasureBand202]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=202
Channel=Auto
HandlerName=ReMaper

[MeasureBand203]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=203
Channel=Auto
HandlerName=ReMaper

[MeasureBand204]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=204
Channel=Auto
HandlerName=ReMaper

[MeasureBand205]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=205
Channel=Auto
HandlerName=ReMaper

[MeasureBand206]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=206
Channel=Auto
HandlerName=ReMaper

[MeasureBand207]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=207
Channel=Auto
HandlerName=ReMaper

[MeasureBand208]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=208
Channel=Auto
HandlerName=ReMaper

[MeasureBand209]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=209
Channel=Auto
HandlerName=ReMaper

[MeasureBand210]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=210
Channel=Auto
HandlerName=ReMaper

[MeasureBand211]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=211
Channel=Auto
HandlerName=ReMaper

[MeasureBand212]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=212
Channel=Auto
HandlerName=ReMaper

[MeasureBand213]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=213
Channel=Auto
HandlerName=ReMaper

[MeasureBand214]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=214
Channel=Auto
HandlerName=ReMaper

[MeasureBand215]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=215
Channel=Auto
HandlerName=ReMaper

[MeasureBand216]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=216
Channel=Auto
HandlerName=ReMaper

[MeasureBand217]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=217
Channel=Auto
HandlerName=ReMaper

[MeasureBand218]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=218
Channel=Auto
HandlerName=ReMaper

[MeasureBand219]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=219
Channel=Auto
HandlerName=ReMaper

[MeasureBand220]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=220
Channel=Auto
HandlerName=ReMaper

[MeasureBand221]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=221
Channel=Auto
HandlerName=ReMaper

[MeasureBand222]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=222
Channel=Auto
HandlerName=ReMaper

[MeasureBand223]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=223
Channel=Auto
HandlerName=ReMaper

[MeasureBand224]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=224
Channel=Auto
HandlerName=ReMaper

[MeasureBand225]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=225
Channel=Auto
HandlerName=ReMaper

[MeasureBand226]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=226
Channel=Auto
HandlerName=ReMaper

[MeasureBand227]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=227
Channel=Auto
HandlerName=ReMaper

[MeasureBand228]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=228
Channel=Auto
HandlerName=ReMaper

[MeasureBand229]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=229
Channel=Auto
HandlerName=ReMaper

[MeasureBand230]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=230
Channel=Auto
HandlerName=ReMaper

[MeasureBand231]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=231
Channel=Auto
HandlerName=ReMaper

[MeasureBand232]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=232
Channel=Auto
HandlerName=ReMaper

[MeasureBand233]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=233
Channel=Auto
HandlerName=ReMaper

[MeasureBand234]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=234
Channel=Auto
HandlerName=ReMaper

[MeasureBand235]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=235
Channel=Auto
HandlerName=ReMaper

[MeasureBand236]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=236
Channel=Auto
HandlerName=ReMaper

[MeasureBand237]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=237
Channel=Auto
HandlerName=ReMaper

[MeasureBand238]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=238
Channel=Auto
HandlerName=ReMaper

[MeasureBand239]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=239
Channel=Auto
HandlerName=ReMaper

[MeasureBand240]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=240
Channel=Auto
HandlerName=ReMaper

[MeasureBand241]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=241
Channel=Auto
HandlerName=ReMaper

[MeasureBand242]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=242
Channel=Auto
HandlerName=ReMaper

[MeasureBand243]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=243
Channel=Auto
HandlerName=ReMaper

[MeasureBand244]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=244
Channel=Auto
HandlerName=ReMaper

[MeasureBand245]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=245
Channel=Auto
HandlerName=ReMaper

[MeasureBand246]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=246
Channel=Auto
HandlerName=ReMaper

[MeasureBand247]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=247
Channel=Auto
HandlerName=ReMaper

[MeasureBand248]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=248
Channel=Auto
HandlerName=ReMaper

[MeasureBand249]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=249
Channel=Auto
HandlerName=ReMaper

[MeasureBand250]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=250
Channel=Auto
HandlerName=ReMaper

[MeasureBand251]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=251
Channel=Auto
HandlerName=ReMaper

[MeasureBand252]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=252
Channel=Auto
HandlerName=ReMaper

[MeasureBand253]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=253
Channel=Auto
HandlerName=ReMaper

[MeasureBand254]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=254
Channel=Auto
HandlerName=ReMaper

[MeasureBand255]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=255
Channel=Auto
HandlerName=ReMaper

[MeasureBand256]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=256
Channel=Auto
HandlerName=ReMaper

[MeasureBand257]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=257
Channel=Auto
HandlerName=ReMaper

[MeasureBand258]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=258
Channel=Auto
HandlerName=ReMaper

[MeasureBand259]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=259
Channel=Auto
HandlerName=ReMaper

[MeasureBand260]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=260
Channel=Auto
HandlerName=ReMaper

[MeasureBand261]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=261
Channel=Auto
HandlerName=ReMaper

[MeasureBand262]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=262
Channel=Auto
HandlerName=ReMaper

[MeasureBand263]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=263
Channel=Auto
HandlerName=ReMaper

[MeasureBand264]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=264
Channel=Auto
HandlerName=ReMaper

[MeasureBand265]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=265
Channel=Auto
HandlerName=ReMaper

[MeasureBand266]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=266
Channel=Auto
HandlerName=ReMaper

[MeasureBand267]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=267
Channel=Auto
HandlerName=ReMaper

[MeasureBand268]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=268
Channel=Auto
HandlerName=ReMaper

[MeasureBand269]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=269
Channel=Auto
HandlerName=ReMaper

[MeasureBand270]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=270
Channel=Auto
HandlerName=ReMaper

[MeasureBand271]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=271
Channel=Auto
HandlerName=ReMaper

[MeasureBand272]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=272
Channel=Auto
HandlerName=ReMaper

[MeasureBand273]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=273
Channel=Auto
HandlerName=ReMaper

[MeasureBand274]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=274
Channel=Auto
HandlerName=ReMaper

[MeasureBand275]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=275
Channel=Auto
HandlerName=ReMaper

[MeasureBand276]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=276
Channel=Auto
HandlerName=ReMaper

[MeasureBand277]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=277
Channel=Auto
HandlerName=ReMaper

[MeasureBand278]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=278
Channel=Auto
HandlerName=ReMaper

[MeasureBand279]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=279
Channel=Auto
HandlerName=ReMaper

[MeasureBand280]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=280
Channel=Auto
HandlerName=ReMaper

[MeasureBand281]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=281
Channel=Auto
HandlerName=ReMaper

[MeasureBand282]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=282
Channel=Auto
HandlerName=ReMaper

[MeasureBand283]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=283
Channel=Auto
HandlerName=ReMaper

[MeasureBand284]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=284
Channel=Auto
HandlerName=ReMaper

[MeasureBand285]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=285
Channel=Auto
HandlerName=ReMaper

[MeasureBand286]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=286
Channel=Auto
HandlerName=ReMaper

[MeasureBand287]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=287
Channel=Auto
HandlerName=ReMaper

[MeasureBand288]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=288
Channel=Auto
HandlerName=ReMaper

[MeasureBand289]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=289
Channel=Auto
HandlerName=ReMaper

[MeasureBand290]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=290
Channel=Auto
HandlerName=ReMaper

[MeasureBand291]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=291
Channel=Auto
HandlerName=ReMaper

[MeasureBand292]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=292
Channel=Auto
HandlerName=ReMaper

[MeasureBand293]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=293
Channel=Auto
HandlerName=ReMaper

[MeasureBand294]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=294
Channel=Auto
HandlerName=ReMaper

[MeasureBand295]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=295
Channel=Auto
HandlerName=ReMaper

[MeasureBand296]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=296
Channel=Auto
HandlerName=ReMaper

[MeasureBand297]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=297
Channel=Auto
HandlerName=ReMaper

[MeasureBand298]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=298
Channel=Auto
HandlerName=ReMaper

[MeasureBand299]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=299
Channel=Auto
HandlerName=ReMaper

[MeasureBand300]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=300
Channel=Auto
HandlerName=ReMaper

[MeasureBand301]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=301
Channel=Auto
HandlerName=ReMaper

[MeasureBand302]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=302
Channel=Auto
HandlerName=ReMaper

[MeasureBand303]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=303
Channel=Auto
HandlerName=ReMaper

[MeasureBand304]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=304
Channel=Auto
HandlerName=ReMaper

[MeasureBand305]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=305
Channel=Auto
HandlerName=ReMaper

[MeasureBand306]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=306
Channel=Auto
HandlerName=ReMaper

[MeasureBand307]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=307
Channel=Auto
HandlerName=ReMaper

[MeasureBand308]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=308
Channel=Auto
HandlerName=ReMaper

[MeasureBand309]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=309
Channel=Auto
HandlerName=ReMaper

[MeasureBand310]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=310
Channel=Auto
HandlerName=ReMaper

[MeasureBand311]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=311
Channel=Auto
HandlerName=ReMaper

[MeasureBand312]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=312
Channel=Auto
HandlerName=ReMaper

[MeasureBand313]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=313
Channel=Auto
HandlerName=ReMaper

[MeasureBand314]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=314
Channel=Auto
HandlerName=ReMaper

[MeasureBand315]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=315
Channel=Auto
HandlerName=ReMaper

[MeasureBand316]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=316
Channel=Auto
HandlerName=ReMaper

[MeasureBand317]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=317
Channel=Auto
HandlerName=ReMaper

[MeasureBand318]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=318
Channel=Auto
HandlerName=ReMaper

[MeasureBand319]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=319
Channel=Auto
HandlerName=ReMaper

[MeasureBand320]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=320
Channel=Auto
HandlerName=ReMaper

[MeasureBand321]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=321
Channel=Auto
HandlerName=ReMaper

[MeasureBand322]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=322
Channel=Auto
HandlerName=ReMaper

[MeasureBand323]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=323
Channel=Auto
HandlerName=ReMaper

[MeasureBand324]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=324
Channel=Auto
HandlerName=ReMaper

[MeasureBand325]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=325
Channel=Auto
HandlerName=ReMaper

[MeasureBand326]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=326
Channel=Auto
HandlerName=ReMaper

[MeasureBand327]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=327
Channel=Auto
HandlerName=ReMaper

[MeasureBand328]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=328
Channel=Auto
HandlerName=ReMaper

[MeasureBand329]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=329
Channel=Auto
HandlerName=ReMaper

[MeasureBand330]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=330
Channel=Auto
HandlerName=ReMaper

[MeasureBand331]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=331
Channel=Auto
HandlerName=ReMaper

[MeasureBand332]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=332
Channel=Auto
HandlerName=ReMaper

[MeasureBand333]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=333
Channel=Auto
HandlerName=ReMaper

[MeasureBand334]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=334
Channel=Auto
HandlerName=ReMaper

[MeasureBand335]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=335
Channel=Auto
HandlerName=ReMaper

[MeasureBand336]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=336
Channel=Auto
HandlerName=ReMaper

[MeasureBand337]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=337
Channel=Auto
HandlerName=ReMaper

[MeasureBand338]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=338
Channel=Auto
HandlerName=ReMaper

[MeasureBand339]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=339
Channel=Auto
HandlerName=ReMaper

[MeasureBand340]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=340
Channel=Auto
HandlerName=ReMaper

[MeasureBand341]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=341
Channel=Auto
HandlerName=ReMaper

[MeasureBand342]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=342
Channel=Auto
HandlerName=ReMaper

[MeasureBand343]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=343
Channel=Auto
HandlerName=ReMaper

[MeasureBand344]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=344
Channel=Auto
HandlerName=ReMaper

[MeasureBand345]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=345
Channel=Auto
HandlerName=ReMaper

[MeasureBand346]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=346
Channel=Auto
HandlerName=ReMaper

[MeasureBand347]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=347
Channel=Auto
HandlerName=ReMaper

[MeasureBand348]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=348
Channel=Auto
HandlerName=ReMaper

[MeasureBand349]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=349
Channel=Auto
HandlerName=ReMaper

[MeasureBand350]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=350
Channel=Auto
HandlerName=ReMaper

[MeasureBand351]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=351
Channel=Auto
HandlerName=ReMaper

[MeasureBand352]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=352
Channel=Auto
HandlerName=ReMaper

[MeasureBand353]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=353
Channel=Auto
HandlerName=ReMaper

[MeasureBand354]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=354
Channel=Auto
HandlerName=ReMaper

[MeasureBand355]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=355
Channel=Auto
HandlerName=ReMaper

[MeasureBand356]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=356
Channel=Auto
HandlerName=ReMaper

[MeasureBand357]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=357
Channel=Auto
HandlerName=ReMaper

[MeasureBand358]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=358
Channel=Auto
HandlerName=ReMaper

[MeasureBand359]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=359
Channel=Auto
HandlerName=ReMaper

[MeasureBand360]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=360
Channel=Auto
HandlerName=ReMaper

[MeasureBand361]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=361
Channel=Auto
HandlerName=ReMaper

[MeasureBand362]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=362
Channel=Auto
HandlerName=ReMaper

[MeasureBand363]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=363
Channel=Auto
HandlerName=ReMaper

[MeasureBand364]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=364
Channel=Auto
HandlerName=ReMaper

[MeasureBand365]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=365
Channel=Auto
HandlerName=ReMaper

[MeasureBand366]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=366
Channel=Auto
HandlerName=ReMaper

[MeasureBand367]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=367
Channel=Auto
HandlerName=ReMaper

[MeasureBand368]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=368
Channel=Auto
HandlerName=ReMaper

[MeasureBand369]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=369
Channel=Auto
HandlerName=ReMaper

[MeasureBand370]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=370
Channel=Auto
HandlerName=ReMaper

[MeasureBand371]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=371
Channel=Auto
HandlerName=ReMaper

[MeasureBand372]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=372
Channel=Auto
HandlerName=ReMaper

[MeasureBand373]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=373
Channel=Auto
HandlerName=ReMaper

[MeasureBand374]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=374
Channel=Auto
HandlerName=ReMaper

[MeasureBand375]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=375
Channel=Auto
HandlerName=ReMaper

[MeasureBand376]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=376
Channel=Auto
HandlerName=ReMaper

[MeasureBand377]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=377
Channel=Auto
HandlerName=ReMaper

[MeasureBand378]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=378
Channel=Auto
HandlerName=ReMaper

[MeasureBand379]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=379
Channel=Auto
HandlerName=ReMaper

[MeasureBand380]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=380
Channel=Auto
HandlerName=ReMaper

[MeasureBand381]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=381
Channel=Auto
HandlerName=ReMaper

[MeasureBand382]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=382
Channel=Auto
HandlerName=ReMaper

[MeasureBand383]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=383
Channel=Auto
HandlerName=ReMaper

[MeasureBand384]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=384
Channel=Auto
HandlerName=ReMaper

[MeasureBand385]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=385
Channel=Auto
HandlerName=ReMaper

[MeasureBand386]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=386
Channel=Auto
HandlerName=ReMaper

[MeasureBand387]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=387
Channel=Auto
HandlerName=ReMaper

[MeasureBand388]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=388
Channel=Auto
HandlerName=ReMaper

[MeasureBand389]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=389
Channel=Auto
HandlerName=ReMaper

[MeasureBand390]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=390
Channel=Auto
HandlerName=ReMaper

[MeasureBand391]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=391
Channel=Auto
HandlerName=ReMaper

[MeasureBand392]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=392
Channel=Auto
HandlerName=ReMaper

[MeasureBand393]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=393
Channel=Auto
HandlerName=ReMaper

[MeasureBand394]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=394
Channel=Auto
HandlerName=ReMaper

[MeasureBand395]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=395
Channel=Auto
HandlerName=ReMaper

[MeasureBand396]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=396
Channel=Auto
HandlerName=ReMaper

[MeasureBand397]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=397
Channel=Auto
HandlerName=ReMaper

[MeasureBand398]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=398
Channel=Auto
HandlerName=ReMaper

[MeasureBand399]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=MeasureAudio
Type=Child
Index=399
Channel=Auto
HandlerName=ReMaper

