[MeterSpectrum]
Meter=Shape
X=300
Y=0
; ---------------------------------------------------------------------------------------------
Shape=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand0])),#Radius# | #Fill# | #Stroke#
; ---------------------------------------------------------------------------------------------
Shape2=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand1])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*1),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape3=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand2])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*2),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape4=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand3])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*3),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape5=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand4])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*4),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape6=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand5])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*5),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape7=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand6])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*6),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape8=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand7])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*7),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape9=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand8])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*8),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape10=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand9])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*9),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape11=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand10])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*10),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape12=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand11])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*11),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape13=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand12])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*12),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape14=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand13])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*13),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape15=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand14])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*14),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape16=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand15])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*15),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape17=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand16])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*16),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape18=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand17])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*17),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape19=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand18])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*18),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape20=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand19])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*19),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape21=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand20])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*20),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape22=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand21])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*21),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape23=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand22])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*22),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape24=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand23])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*23),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape25=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand24])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*24),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape26=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand25])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*25),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape27=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand26])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*26),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape28=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand27])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*27),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape29=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand28])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*28),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape30=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand29])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*29),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape31=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand30])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*30),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape32=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand31])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*31),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape33=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand32])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*32),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape34=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand33])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*33),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape35=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand34])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*34),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape36=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand35])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*35),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape37=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand36])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*36),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape38=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand37])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*37),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape39=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand38])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*38),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape40=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand39])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*39),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape41=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand40])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*40),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape42=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand41])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*41),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape43=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand42])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*42),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape44=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand43])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*43),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape45=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand44])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*44),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape46=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand45])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*45),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape47=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand46])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*46),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape48=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand47])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*47),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape49=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand48])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*48),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape50=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand49])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*49),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape51=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand50])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*50),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape52=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand51])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*51),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape53=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand52])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*52),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape54=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand53])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*53),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape55=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand54])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*54),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape56=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand55])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*55),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape57=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand56])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*56),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape58=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand57])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*57),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape59=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand58])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*58),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape60=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand59])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*59),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape61=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand60])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*60),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape62=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand61])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*61),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape63=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand62])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*62),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape64=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand63])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*63),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape65=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand64])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*64),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape66=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand65])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*65),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape67=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand66])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*66),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape68=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand67])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*67),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape69=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand68])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*68),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape70=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand69])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*69),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape71=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand70])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*70),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape72=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand71])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*71),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape73=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand72])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*72),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape74=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand73])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*73),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape75=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand74])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*74),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape76=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand75])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*75),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape77=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand76])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*76),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape78=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand77])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*77),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape79=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand78])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*78),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape80=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand79])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*79),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape81=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand80])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*80),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape82=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand81])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*81),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape83=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand82])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*82),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape84=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand83])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*83),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape85=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand84])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*84),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape86=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand85])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*85),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape87=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand86])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*86),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape88=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand87])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*87),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape89=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand88])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*88),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape90=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand89])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*89),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape91=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand90])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*90),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape92=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand91])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*91),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape93=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand92])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*92),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape94=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand93])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*93),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape95=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand94])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*94),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape96=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand95])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*95),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape97=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand96])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*96),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape98=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand97])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*97),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape99=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand98])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*98),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape100=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand99])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*99),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape101=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand100])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*100),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape102=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand101])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*101),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape103=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand102])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*102),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape104=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand103])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*103),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape105=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand104])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*104),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape106=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand105])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*105),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape107=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand106])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*106),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape108=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand107])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*107),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape109=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand108])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*108),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape110=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand109])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*109),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape111=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand110])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*110),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape112=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand111])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*111),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape113=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand112])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*112),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape114=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand113])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*113),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape115=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand114])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*114),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape116=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand115])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*115),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape117=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand116])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*116),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape118=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand117])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*117),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape119=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand118])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*118),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape120=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand119])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*119),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape121=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand120])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*120),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape122=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand121])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*121),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape123=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand122])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*122),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape124=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand123])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*123),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape125=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand124])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*124),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape126=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand125])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*125),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape127=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand126])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*126),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape128=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand127])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*127),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape129=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand128])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*128),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape130=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand129])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*129),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape131=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand130])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*130),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape132=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand131])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*131),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape133=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand132])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*132),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape134=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand133])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*133),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape135=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand134])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*134),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape136=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand135])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*135),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape137=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand136])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*136),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape138=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand137])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*137),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape139=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand138])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*138),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape140=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand139])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*139),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape141=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand140])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*140),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape142=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand141])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*141),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape143=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand142])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*142),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape144=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand143])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*143),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape145=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand144])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*144),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape146=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand145])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*145),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape147=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand146])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*146),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape148=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand147])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*147),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape149=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand148])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*148),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape150=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand149])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*149),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape151=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand150])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*150),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape152=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand151])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*151),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape153=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand152])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*152),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape154=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand153])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*153),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape155=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand154])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*154),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape156=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand155])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*155),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape157=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand156])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*156),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape158=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand157])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*157),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape159=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand158])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*158),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape160=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand159])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*159),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape161=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand160])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*160),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape162=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand161])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*161),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape163=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand162])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*162),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape164=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand163])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*163),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape165=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand164])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*164),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape166=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand165])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*165),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape167=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand166])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*166),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape168=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand167])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*167),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape169=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand168])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*168),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape170=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand169])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*169),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape171=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand170])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*170),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape172=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand171])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*171),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape173=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand172])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*172),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape174=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand173])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*173),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape175=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand174])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*174),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape176=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand175])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*175),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape177=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand176])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*176),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape178=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand177])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*177),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape179=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand178])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*178),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape180=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand179])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*179),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape181=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand180])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*180),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape182=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand181])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*181),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape183=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand182])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*182),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape184=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand183])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*183),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape185=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand184])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*184),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape186=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand185])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*185),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape187=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand186])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*186),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape188=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand187])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*187),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape189=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand188])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*188),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape190=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand189])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*189),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape191=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand190])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*190),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape192=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand191])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*191),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape193=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand192])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*192),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape194=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand193])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*193),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape195=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand194])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*194),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape196=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand195])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*195),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape197=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand196])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*196),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape198=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand197])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*197),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape199=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand198])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*198),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape200=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand199])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*199),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape201=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand200])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*200),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape202=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand201])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*201),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape203=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand202])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*202),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape204=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand203])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*203),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape205=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand204])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*204),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape206=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand205])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*205),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape207=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand206])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*206),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape208=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand207])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*207),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape209=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand208])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*208),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape210=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand209])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*209),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape211=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand210])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*210),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape212=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand211])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*211),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape213=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand212])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*212),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape214=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand213])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*213),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape215=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand214])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*214),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape216=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand215])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*215),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape217=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand216])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*216),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape218=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand217])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*217),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape219=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand218])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*218),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape220=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand219])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*219),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape221=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand220])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*220),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape222=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand221])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*221),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape223=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand222])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*222),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape224=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand223])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*223),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape225=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand224])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*224),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape226=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand225])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*225),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape227=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand226])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*226),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape228=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand227])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*227),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape229=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand228])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*228),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape230=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand229])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*229),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape231=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand230])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*230),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape232=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand231])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*231),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape233=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand232])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*232),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape234=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand233])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*233),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape235=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand234])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*234),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape236=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand235])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*235),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape237=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand236])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*236),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape238=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand237])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*237),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape239=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand238])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*238),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape240=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand239])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*239),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape241=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand240])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*240),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape242=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand241])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*241),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape243=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand242])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*242),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape244=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand243])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*243),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape245=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand244])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*244),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape246=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand245])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*245),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape247=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand246])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*246),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape248=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand247])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*247),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape249=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand248])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*248),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape250=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand249])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*249),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape251=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand250])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*250),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape252=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand251])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*251),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape253=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand252])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*252),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape254=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand253])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*253),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape255=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand254])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*254),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape256=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand255])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*255),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape257=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand256])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*256),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape258=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand257])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*257),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape259=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand258])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*258),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape260=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand259])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*259),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape261=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand260])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*260),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape262=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand261])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*261),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape263=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand262])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*262),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape264=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand263])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*263),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape265=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand264])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*264),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape266=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand265])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*265),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape267=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand266])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*266),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape268=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand267])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*267),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape269=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand268])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*268),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape270=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand269])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*269),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape271=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand270])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*270),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape272=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand271])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*271),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape273=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand272])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*272),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape274=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand273])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*273),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape275=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand274])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*274),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape276=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand275])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*275),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape277=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand276])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*276),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape278=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand277])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*277),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape279=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand278])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*278),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape280=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand279])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*279),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape281=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand280])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*280),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape282=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand281])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*281),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape283=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand282])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*282),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape284=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand283])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*283),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape285=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand284])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*284),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape286=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand285])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*285),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape287=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand286])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*286),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape288=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand287])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*287),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape289=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand288])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*288),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape290=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand289])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*289),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape291=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand290])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*290),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape292=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand291])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*291),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape293=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand292])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*292),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape294=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand293])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*293),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape295=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand294])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*294),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape296=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand295])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*295),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape297=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand296])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*296),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape298=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand297])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*297),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape299=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand298])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*298),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape300=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand299])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*299),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape301=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand300])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*300),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape302=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand301])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*301),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape303=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand302])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*302),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape304=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand303])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*303),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape305=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand304])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*304),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape306=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand305])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*305),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape307=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand306])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*306),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape308=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand307])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*307),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape309=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand308])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*308),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape310=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand309])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*309),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape311=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand310])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*310),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape312=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand311])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*311),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape313=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand312])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*312),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape314=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand313])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*313),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape315=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand314])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*314),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape316=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand315])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*315),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape317=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand316])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*316),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape318=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand317])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*317),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape319=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand318])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*318),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape320=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand319])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*319),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape321=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand320])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*320),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape322=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand321])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*321),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape323=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand322])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*322),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape324=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand323])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*323),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape325=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand324])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*324),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape326=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand325])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*325),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape327=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand326])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*326),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape328=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand327])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*327),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape329=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand328])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*328),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape330=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand329])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*329),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape331=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand330])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*330),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape332=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand331])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*331),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape333=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand332])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*332),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape334=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand333])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*333),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape335=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand334])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*334),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape336=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand335])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*335),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape337=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand336])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*336),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape338=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand337])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*337),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape339=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand338])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*338),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape340=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand339])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*339),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape341=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand340])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*340),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape342=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand341])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*341),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape343=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand342])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*342),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape344=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand343])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*343),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape345=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand344])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*344),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape346=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand345])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*345),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape347=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand346])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*346),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape348=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand347])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*347),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape349=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand348])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*348),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape350=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand349])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*349),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape351=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand350])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*350),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape352=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand351])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*351),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape353=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand352])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*352),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape354=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand353])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*353),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape355=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand354])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*354),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape356=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand355])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*355),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape357=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand356])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*356),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape358=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand357])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*357),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape359=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand358])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*358),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape360=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand359])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*359),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape361=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand360])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*360),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape362=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand361])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*361),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape363=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand362])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*362),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape364=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand363])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*363),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape365=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand364])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*364),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape366=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand365])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*365),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape367=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand366])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*366),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape368=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand367])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*367),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape369=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand368])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*368),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape370=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand369])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*369),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape371=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand370])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*370),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape372=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand371])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*371),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape373=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand372])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*372),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape374=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand373])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*373),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape375=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand374])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*374),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape376=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand375])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*375),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape377=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand376])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*376),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape378=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand377])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*377),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape379=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand378])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*378),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape380=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand379])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*379),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape381=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand380])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*380),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape382=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand381])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*381),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape383=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand382])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*382),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape384=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand383])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*383),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape385=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand384])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*384),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape386=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand385])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*385),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape387=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand386])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*386),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape388=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand387])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*387),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape389=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand388])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*388),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape390=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand389])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*389),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape391=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand390])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*390),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape392=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand391])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*391),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape393=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand392])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*392),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape394=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand393])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*393),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape395=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand394])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*394),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape396=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand395])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*395),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape397=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand396])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*396),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape398=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand397])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*397),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape399=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand398])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*398),(#BarYR#)
; ---------------------------------------------------------------------------------------------
Shape400=Rectangle #BarX#,#MaxHeight#,#BarWidth#,(Neg([MeasureBand399])),#Radius# | #Fill# | #Stroke# | Offset (#BarXR#*399),(#BarYR#)
; ---------------------------------------------------------------------------------------------
DynamicVariables=1
